apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: test-go
    image: quay.io/hongkailiu/test-go:http-0.0.23-730e2a2c
    command: ["/http"]
    args: ["start", "-v"]
    env:
    - name: GIN_MODE
      value: release
    ports:
    - containerPort: 8080
