apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: test-go
    image: quay.io/hongkailiu/test-go:testctl-0.0.3-71e8cd9c
    command: ["/testctl"]
    args: ["http", "start", "-v"]
    env:
    - name: GIN_MODE
      value: release
    ports:
    - containerPort: 8080
