### not working: permission issue
### https://severalnines.com/blog/using-kubernetes-deploy-postgresql
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    name: postgresql-persistent
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: postgres-config
    labels:
      app: postgres
  data:
    POSTGRES_DB: ${POSTGRESQL_DATABASE}
    POSTGRES_USER: ${POSTGRESQL_USER}
    POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: postgres-pv-claim
    labels:
      app: postgres
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: postgres
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: postgres
            image: docker.io/postgres:11
            imagePullPolicy: "IfNotPresent"
            ports:
              - containerPort: 5432
            envFrom:
              - configMapRef:
                  name: postgres-config
#            volumeMounts:
#              - mountPath: /var/lib/postgresql/data
#                name: postgredb
#        volumes:
#          - name: postgredb
#            persistentVolumeClaim:
#              claimName: postgres-pv-claim
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
    labels:
      app: postgres
  spec:
    type: ClusterIP
    ports:
    - name: postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
parameters:
- description: Username for PostgreSQL user that will be used for accessing the database.
  displayName: PostgreSQL Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: POSTGRESQL_USER
  required: true
- description: Password for the PostgreSQL connection user.
  displayName: PostgreSQL Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: POSTGRESQL_PASSWORD
  required: true
- description: Name of the PostgreSQL database accessed.
  displayName: PostgreSQL Database Name
  name: POSTGRESQL_DATABASE
  required: true
  value: sampledb
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi