###$ ansible-playbook -i "ec2-18-236-85-195.us-west-2.compute.amazonaws.com," playbooks/install_fedora_ocp4.yaml -e "aws_access_key_id=aaa aws_secret_access_key=bbb"
### https://gist.github.com/alces/caa3e7e5f46f9595f715f0f55eef65c1

---
- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: hongkliu
    ansible_become_pass: 111
  tasks:
  - name: print hostname
    debug:
      msg: "hostname: {{ inventory_hostname }}"

 