### $ sudo dnf install -y git ansible
### $ git clone https://github.com/hongkailiu/svt-case-doc.git
### $ git clone https://gitlab.com/hongkailiu/svt-secret.git
### $ ansible-playbook ./svt-case-doc/playbooks/install_fedora_internal.yaml -e "ansible_become_pass=<secret>"

---
### https://gist.github.com/alces/caa3e7e5f46f9595f715f0f55eef65c1
- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: hongkliu
    ansible_become_pass: 111
    redhat_internal_cert_rpm: "/home/hongkliu/repo/me/svt-secret/rh_vpn_rpm/redhat-internal-cert-install-0.1-9.el7.csb.noarch.rpm"
    redhat_internal_NetworkManager_openvpn_profiles_rpm: "/home/hongkliu/repo/me/svt-secret/rh_vpn_rpm/redhat-internal-NetworkManager-openvpn-profiles-0.1-30.el7.csb.noarch.rpm"
  tasks:
  - name: print hostname
    debug:
      msg: "hostname: {{ inventory_hostname }}"

  - name: dnf pkgs
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - "{{ redhat_internal_cert_rpm }}"
        - "{{ redhat_internal_NetworkManager_openvpn_profiles_rpm }}"
    become: true

### https://www.if-not-true-then-false.com/2010/install-google-chrome-with-yum-on-fedora-red-hat-rhel/
### chrome
### sudo dnf install fedora-workstation-repositories
### dnf config-manager --set-enabled google-chrome
### sudo dnf config-manager --set-enabled google-chrome
### sudo dnf install google-chrome-stable

### vscode
### sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
### sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
### sudo dnf install code
### https://github.com/Microsoft/vscode/issues/37888

### bluejeans cannot share the entire screen
### https://community.bluejeans.com/bluejeans/topics/screenshare-not-visible-to-participants

